version: 2.1

jobs:
  fetch_files:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Check external IP address
          command: |
            curl --retry 5 ipconfig.io
      - run:
          name: Fetch files
          command: |
            curl --retry 5 https://dnsjson.com/jobs.knownips.circleci.com/A.json

workflows:
  main:
    jobs:
      - fetch_files
